name: Pull request to master

on:
  pull_request:
    branches:
      - master
    types:
      - opened

permissions:
  contents: read

jobs:
  pull-request-opened:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm pull request trigger
        run: echo "Pull request #${{ github.event.pull_request.number }} was opened against master"
